/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./index-formatted.html",
    "./gift.html",
    "./gift-formatted.html",
    "./about.html",
    "./about-formatted.html",
    "./policy.html",
    "./policy-formatted.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#837375",
        "surface-bright": "#fff8f8",
        "on-primary": "#ffffff",
        secondary: "#5c5d6e",
        background: "#fff8f8",
        "on-secondary-fixed": "#191b29",
        "on-error": "#ffffff",
        "surface-container": "#fee8ef",
        "secondary-fixed": "#e1e1f5",
        "on-surface": "#24181d",
        "surface-container-high": "#f9e3ea",
        "inverse-on-surface": "#ffecf2",
        "primary-container": "#ffc1cc",
        "inverse-surface": "#3a2d32",
        surface: "#fff8f8",
        "surface-variant": "#f3dde4",
        "secondary-container": "#e1e1f5",
        "tertiary-container": "#d5d0c8",
        "on-tertiary-fixed": "#1d1b16",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0f4",
        "on-primary-fixed-variant": "#663a43",
        "on-error-container": "#93000a",
        "on-primary-container": "#7b4c56",
        "error-container": "#ffdad6",
        "on-secondary-container": "#626374",
        "on-surface-variant": "#514345",
        "tertiary-fixed-dim": "#cbc6bd",
        "surface-dim": "#ead5dc",
        "outline-variant": "#d5c2c4",
        "on-tertiary-fixed-variant": "#494640",
        tertiary: "#615e57",
        "on-tertiary-container": "#5c5952",
        primary: "#81515b",
        "inverse-primary": "#f3b7c1",
        "secondary-fixed-dim": "#c5c5d8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e7e2d9",
        "surface-tint": "#81515b",
        "primary-fixed-dim": "#f3b7c1",
        "on-primary-fixed": "#331019",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#444655",
        "on-background": "#24181d",
        "surface-container-highest": "#f3dde4",
        "primary-fixed": "#ffd9df",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "section-gap-desktop": "120px",
        "section-gap-mobile": "64px",
        "element-gap": "16px",
        "container-padding": "24px",
      },
      fontFamily: {
        "label-md": ["Quicksand"],
        "body-md": ["Outfit"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Outfit"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      animation: {
        "float": "float 3s ease-in-out infinite",
        "heart-pop": "heart-pop 0.6s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "sparkle": "sparkle 2s ease-in-out",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "heart-pop": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.3)" },
          "100%": { transform: "scale(1)" },
        },
        sparkle: {
          "0%": { opacity: "0", transform: "scale(0)" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
